repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
releases:
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.12.1
    namespace: ingress-nginx
    kubeContext: rpi
    createNamespace: true
    values:
      - controller:
          image:
            # supposed to be a best practice but needs more configuration i guess since it crashes on startup
            readOnlyRootFilesystem: false

          securityContext:
#            capabilities:
#              add: []
#          hostNetwork: true
#          dnsPolicy: ClusterFirstWithHostNet
          allowSnippetAnnotations: true
          kind: Deployment
          service:
            enabled: true
#            loadBalancerIP: 192.168.1.8
#            externalIPs:
#              - 192.168.1.8
            annotations:
              metallb.universe.tf/allow-shared-ip: 192.168.1.8
              ad.datadoghq.com/controller.logs: '[{"source": "nginx", "service": "ingress-nginx"}]'