repositories:
  ingress-nginx: https://kubernetes.github.io/ingress-nginx
releases:
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 2.0.1
    namespace: ingress-nginx
    createNamespace: true
    values:
      - controller:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          enableSnippets: true
          kind: daemonset
          service:
            enabled: true
            loadBalancerIP: 192.168.1.8
            annotations:
              metallb.universe.tf/allow-shared-ip: 192.168.1.8
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE