repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: oauth2-proxy
    kubeContext: rpi
    chart: bitnami/oauth2-proxy
    version: 6.2.11
    namespace: longhorn-system
    values:
      - redis:
          enabled: false
      - configuration:
          clientID: {{ exec "op" (list "read" "--no-newline" "op://Private/4vowpk2pjbbegc4wnwrz6s4mg4/client-id") | quote }}
          clientSecret: {{ exec "op" (list "read" "--no-newline" "op://Private/4vowpk2pjbbegc4wnwrz6s4mg4/client-secret") | quote }}
          cookieSecret: {{ exec "op" (list "read" "--no-newline" "op://Private/4vowpk2pjbbegc4wnwrz6s4mg4/cookie-secret") | quote  }}
#          google:
#            enabled: true
#            adminEmail: csl4jc@gmail.com
#            serviceAccountJson: {{ exec "op" (list "read" "op://Private/4vowpk2pjbbegc4wnwrz6s4mg4/service-account-json") | quote }}
          emailDomains:
            - csl4jc@gmail.com # Only allow your email
          whitelistDomains:
            - .home.planetlauritsen.com
      - extraVolumes:
          - name: allowed-emails
            configMap:
              name: allowed-emails
      - extraVolumeMounts:
          - name: allowed-emails
            mountPath: /etc/oauth2-proxy
      - extraArgs:
          - --cookie-secure=true
          - --cookie-samesite=lax
          - --cookie-domain=.planetlauritsen.com
          - --set-authorization-header=true
          - --pass-access-token=true
          - --whitelist-domain=*.home.planetlauritsen.com
          - --show-debug-on-error=true
          - --standard-logging=true
          - --auth-logging=true
          - --request-logging=true
          - --provider=google
          - --authenticated-emails-file=/etc/oauth2-proxy/allowed-emails.txt


      - ingress:
          enabled: true
          tls: true
          selfSigned: true
          hostname: oauth2-proxy.home.planetlauritsen.com
          ingressClassName: nginx
          existingSecretName: wildcard-home-planetlauritsen-tls
#          path: /
#          hosts:
#            - longhorn.home.planetlauritsen.com
#          tls:
#            - hosts:
#                - longhorn.home.planetlauritsen.com
#              secretName: wildcard-home-planetlauritsen-tls
