repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: oauth2-proxy-config
    kubeContext: rpi
    chart: ./rsrc
    namespace: oauth2-proxy
  - name: oauth2-proxy
    kubeContext: rpi
    chart: bitnami/oauth2-proxy
    version: 6.2.11
    namespace: oauth2-proxy
    createNamespace: true
    values:
      - global:
          security:
            allowInsecureImages: true
      - image:
            registry: quay.io
            repository: oauth2-proxy/oauth2-proxy
            tag: latest
      - redis:
          enabled: false
      - configuration:
          clientID: {{ exec "op" (list "read" "--no-newline" "op://Private/4vowpk2pjbbegc4wnwrz6s4mg4/client-id") | quote }}
          clientSecret: {{ exec "op" (list "read" "--no-newline" "op://Private/4vowpk2pjbbegc4wnwrz6s4mg4/client-secret") | quote }}
          cookieSecret: {{ exec "op" (list "read" "--no-newline" "op://Private/4vowpk2pjbbegc4wnwrz6s4mg4/cookie-secret") | quote  }}
          whitelistDomains:
            - .home.planetlauritsen.com
      - extraVolumes:
          - name: allowed-emails
            configMap:
              name: allowed-emails
      - extraVolumeMounts:
          - name: allowed-emails
            mountPath: /etc/oauth2-proxy
      - extraArgs:
          - --cookie-secure=true
          - --cookie-samesite=lax
          - --cookie-domain=.planetlauritsen.com
          - --set-authorization-header=true
          - --pass-access-token=true
          - --whitelist-domain=*.home.planetlauritsen.com
          - --standard-logging=true
          - --auth-logging=true
          - --request-logging=true
          - --provider=google
          - --authenticated-emails-file=/etc/oauth2-proxy/allowed-emails.txt
          - --email-domain=
          - --show-debug-on-error
      - ingress:
          enabled: true
          tls: true
          selfSigned: false
          hostname: oauth2-proxy.home.planetlauritsen.com
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns
          extraTls:
            - hosts:
                - oauth2-proxy.home.planetlauritsen.com
              secretName: oauth2-proxy-tls # pragma: allowlist secret
