- import_playbook: playbooks/common/apt-update.yaml
- import_playbook: playbooks/k3s-prepare/docker.yaml
- import_playbook: playbooks/k3s-prepare/k3s-server.yaml
- import_playbook: playbooks/k3s-prepare/k3s-workers.yaml