apiVersion: v1
kind: Service
metadata:
  name: mongo-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.1.9
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/name: mongodb
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017