{{- if .Values.certManager }}
{{- $fullname := include "james.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{$fullname}}-cert
spec:
  secretName: {{$fullname}}-tls-secret
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: imap.home.planetlauritsen.com
  dnsNames:
  - imap.home.planetlauritsen.com
  - smtp.home.planetlauritsen.com
  {{- end }}