apiVersion: v1
kind: Service
metadata:
  name: {{ include "james.fullname" . }}
  labels:
    {{- include "james.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: imap
      protocol: TCP
      port: 143
    - name: imaps
      protocol: TCP
      port: 993
    - name: pop3
      protocol: TCP
      port: 110
    - name: smtp
      protocol: TCP
      port: 25
    - name: smtpauth
      protocol: TCP
      port: 587
    - name: smtps
      protocol: TCP
      port: 465
  selector:
    {{- include "james.selectorLabels" . | nindent 4 }}
