releases:
  - name: roundcube
    namespace: roundcube
    chart: ./chart
    kubeContext: rpi
    values:
      - pvc:
          storageClassName: longhorn
      - env:
          ROUNDCUBEMAIL_DEFAULT_HOST: james.james
          ROUNDCUBEMAIL_SMTP_SERVER: james.james
          ROUNDCUBEMAIL_SMTP_PORT: "587"
          # i think it worked with out this
          #ROUNDCUBEMAIL_SMTP_USE_TLS: "true"

#            - env: │
#          │     - name: ROUNDCUBEMAIL_DEFAULT_HOST                                                                                                                                                                                                                                                                                   │
#          │       value: james.james                                                                                                                                                                                                                                                                                                 │
#          │     - name: ROUNDCUBEMAIL_SMTP_SERVER                                                                                                                                                                                                                                                                                    │
#          │       value: tls://james.james                                                                                                                                                                                                                                                                                           │
#          │     - name: ROUNDCUBEMAIL_SMTP_PORT                                                                                                                                                                                                                                                                                      │
#          │       value: "587"
      - ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns
          hosts:
            - host: mail.home.planetlauritsen.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: roundcube-tls
              hosts:
                - mail.home.planetlauritsen.com
