releases:
  - name: jim-bridger
    chart: oci://docker.io/cslauritsen/jim-bridger-chart
    version: 0.1.7
    kubeContext: rpi
    labels:
      cat: main
    namespace: james
    createNamespace: false
    values:
      - fullnameOverride: jim-bridger
      - smtp:
          host: james
      - ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns
          hosts:
            - host: jim-bridger.home.planetlauritsen.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: jim-bridger-tls
              hosts:
                - jim-bridger.home.planetlauritsen.com
