apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cslauritsen/ansible-home.git
    targetRevision: HEAD
    path: helmfile/alloy
    plugin:
      name: helmfile
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # Manual sync initially - enable automated sync after validation
    # automated:
    #   prune: true
    #   selfHeal: true

