apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-lb
  namespace: rabbitmq
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.1.9
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.9
  selector:
    statefulset.kubernetes.io/pod-name: rabbitmq-0
  ports:
    - name: epmd
      protocol: TCP
      port: 4369
    - name: amqp
      protocol: TCP
      port: 5672
    - name: dist
      protocol: TCP
      port: 25672
    - name: http-stats
      protocol: TCP
      port: 15672