apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: james
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.1.9
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.9
  selector:
    statefulset.kubernetes.io/pod-name: james-postgresql-0
  ports:
#    - name: intra
#      protocol: TCP
#      port: 7000
#    - name: jmx
#      protocol: TCP
#      port: 7199
    - name: tcp-postgresql
      protocol: TCP
      port: 5432