apiVersion: v1
kind: Service
metadata:
  name: coredns-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.1.9
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.9
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
