apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  home.server: |
    home.planetlauritsen.com:53 {
      template IN A {
          match ^([a-z].+)\.home\.planetlauritsen\.com\.$
          answer "{{ .Name }} 60 IN A 192.168.1.8"
          fallthrough
      }
      log
      errors
      forward . 1.1.1.1 8.8.8.8
    }

  acme-challenge.server: |
    _acme-challenge.home.planetlauritsen.com:53 {
      forward . 1.1.1.1 8.8.8.8
      log
      errors
    }

  apex.server: |
    planetlauritsen.com:53 {
      forward . 1.1.1.1 8.8.8.8
      log
      errors
    }
