apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/cslauritsen/ansible-home.git
      targetRevision: main
      path: argocd/charts/headlamp/chart
      helm:
        valueFiles:
          - ../values-rpi.yaml
    - repoURL: https://github.com/cslauritsen/ansible-home.git
      targetRevision: main
      path: argocd/charts/headlamp/rsrc  # ← Adds the SealedSecret

  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp  # ← Changed from kube-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  # ← Changed to true
    automated:
      prune: true
      selfHeal: true
