apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/cslauritsen/ansible-home.git
      targetRevision: main
      path: argocd/charts/sealed-secrets/chart
      helm:
        valueFiles:
          - $values/argocd/charts/sealed-secrets/values-rpi.yaml
    - repoURL: https://github.com/cslauritsen/ansible-home.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # Manual sync initially - enable automated sync after validation
    automated:
     prune: true
     selfHeal: true

