repositories:
  - name: grafana 
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana-k8s-monitoring
    namespace: o11y
    createNamespace: true
    atomic: false
    version: '^2'
    chart: grafana/k8s-monitoring
#  helm upgrade --install --version ^2 --atomic --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring \
#    --namespace "o11y" --create-namespace --values - <<'EOF'
    values:
      - cluster:
          name: rpi
        destinations:
          - name: grafana-cloud-metrics
            type: prometheus
            url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
            auth:
              type: basic
              username: "2419169"
              password: {{ exec "op" (list "read" "--no-newline"  "op://Private/n4b33z3lps73pnkdmyawdxfdoq/password") | quote }}
          - name: grafana-cloud-logs
            type: loki
            url: https://logs-prod-036.grafana.net/loki/api/v1/push
            auth:
              type: basic
              username: "1205261"
              password: {{ exec "op" (list "read" "--no-newline" "op://Private/n4b33z3lps73pnkdmyawdxfdoq/password") | quote }}
          - name: grafana-cloud-traces
            type: otlp
            url: https://tempo-prod-26-prod-us-east-2.grafana.net:443
            protocol: grpc
            auth:
              type: basic
              username: "1199572"
              password: {{ exec "op" (list "read" "--no-newline" "op://Private/n4b33z3lps73pnkdmyawdxfdoq/password") | quote }}
            metrics:
              enabled: false
            logs:
              enabled: false
            traces:
              enabled: true
          - name: grafana-cloud-profiles
            type: pyroscope
            url: https://profiles-prod-001.grafana.net:443
            auth:
              type: basic
              username: "1247466"
              password: {{ exec "op" (list "read" "--no-newline" "op://Private/n4b33z3lps73pnkdmyawdxfdoq/password") | quote }}
        clusterMetrics:
          enabled: true
          opencost:
            enabled: true
            metricsSource: grafana-cloud-metrics
            opencost:
              exporter:
                defaultClusterId: rpi
              prometheus:
                existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
                external:
                  url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom
          kepler:
            enabled: false
        annotationAutodiscovery:
          enabled: true
        prometheusOperatorObjects:
          enabled: true
        clusterEvents:
          enabled: true
        nodeLogs:
          enabled: true
        podLogs:
          enabled: true
        applicationObservability:
          enabled: true
          receivers:
            otlp:
              grpc:
                enabled: true
                port: 4317
              http:
                enabled: true
                port: 4318
            zipkin:
              enabled: true
              port: 9411
          connectors:
            grafanaCloudMetrics:
              enabled: true
        autoInstrumentation:
          enabled: false
        profiling:
          enabled: true
        integrations:
          alloy:
            instances:
              - name: alloy
                labelSelectors:
                  app.kubernetes.io/name:
                    - alloy-metrics
                    - alloy-singleton
                    - alloy-logs
                    - alloy-receiver
                    - alloy-profiles
        alloy-metrics:
          enabled: true
        alloy-singleton:
          enabled: true
        alloy-logs:
          enabled: true
        alloy-receiver:
          enabled: true
          alloy:
            extraPorts:
              - name: otlp-grpc
                port: 4317
                targetPort: 4317
                protocol: TCP
              - name: otlp-http
                port: 4318
                targetPort: 4318
                protocol: TCP
              - name: zipkin
                port: 9411
                targetPort: 9411
                protocol: TCP
        alloy-profiles:
          enabled: true

