apiVersion: v1
kind: Service
metadata:
  name: squid-lb
  annotations:
    metallb.io/ip-allocated-from-pool: nine
    metallb.io/allow-shared-ip: 192.168.1.9
spec:
  type: LoadBalancer
  ports:
    - port: 3128
      targetPort: 3128
      protocol: TCP
      name: squid
  selector:
    app.kubernetes.io/name: squid
    app.kubernetes.io/instance: squid