- name: Update all packages to the latest version
  hosts: rpi-cluster
  tasks:
   - name: Apt upgrade
     become: yes
     ansible.builtin.apt:
       update_cache: yes
       upgrade: dist
       autoremove: yes
