- name: Install k3s server
  hosts: pi-a
  become: yes
  tasks:
    - name: install k3s
      args:
        creates: /var/lib/rancher/k3s/server/node-token
      ansible.builtin.shell: |
        curl -L https://get.k3s.io \
          | K3S_TOKEN={{ lookup('file', 'k3s_token.txt') }} sh -

- name: Download & Encrypt kubeconfig
  hosts: pi-a
  become: yes
  tasks:
    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./rpi-kubeconfig.yaml
        flat: yes

