postgresql:
  postgresqlUsername: james
  postgresqlPassword: jamespassword
  postgresqlDatabase: jamesdb
  primary:
    persistence:
      storageClass: local-path

minio:
  accessKey: minio
  secretKey: minio123

james:
  image: apache/james
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
